figure5()
print('-dpdf', 'paper-fig5.pdf')
figure6()
print('-dpdf', 'paper-fig6.pdf')
figure7()
print('-dpdf', 'paper-fig7.pdf')
figure8()
print('-dpdf', 'paper-fig8.pdf')
figure9()
print('-dpdf', 'paper-fig9.pdf')
figure10()
print('-dpdf', 'paper-fig10.pdf')